Add configurations
idzm/neuroPID pull request #3
Opened 2024-02-09 06:36 UTC by NogameNo-life

2024-03-01 05:10 UTC, idzm requested changes

2024-03-01 05:10 UTC, idzm commented on CMakeLists.txt
> +add_executable(neuroPID WIN32 src/mlp.cpp src/nn_manager.cpp src/PID.cpp src/plant.cpp src/sample.cpp src/stdafx.cpp "src/main.cpp" src/neuroPID.rc)
```suggestion
add_executable(neuroPID WIN32 src/mlp.cpp src/nn_manager.cpp src/PID.cpp src/plant.cpp src/sample.cpp src/stdafx.cpp src/main.cpp src/neuroPID.rc)
```

2024-03-01 05:10 UTC, idzm commented on src/RCa24704
Что это за файл?

2024-03-01 05:27 UTC, NogameNo-life commented on src/RCa24704
Он там был, это не мое, честно

2024-03-18 07:09 UTC, idzm approved these changes

2024-03-18 07:09 UTC, merged